/*
 * FediFerry — share a meme screenshot straight to Mastodon.
 * Copyright (C) 2026 Jasper Ramthun
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package app.fediferry.ai

import java.util.Base64

/**
 * What a model test sends: a 256-pixel picture of a red circle on blue with a
 * small white label, and masks marking that label for each mask style. Under
 * a kilobyte each, so a test costs next to nothing.
 */
internal object ModelTestImages {
    val picture: ByteArray by lazy { decode("iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAIAAADTED8xAAADAUlEQVR42u3dsZHqMBSGUZlxRU7owPSiQNRCol7owE5cEx14SMzY/OfEL0Da++mys8Eb5rYUSHVzBQgABAACAAGAAEAAIAAQAAgABAACAAGAAEAAIAAQAAgABADnN7qCfe/X/epHeDxXP0cbAAQAAgABgAAQgCtAACAAEAAIAAQAAgABgABAACAAEAAIAAQAAgABgABAACAAOL9hbotbwAYAAYAAQAAgABAACAAEAAIAAYAAQAAgABAACAAEAAIAAYAAQAAgABAACAAEAAIAAYAAQAAgABAACAAEAIcZXcHP9K1+/4/r1N1Y8T/E5Ey8HgRg7pUgAHOvBAEYfRkIwOjLQABGXwYCMPoyKP4QZvr/4xPaAEbfKrABTL/PLACT5JP7CmSAfB2yAUy/swjAxDiRAMyKcwnAlDidAMyHMwoABOBpdFIBmAnnFYBpcGoBgAA8hM4uABPgBgQAAvD4uQcBgAA8e25DACAAD547EQAIwFPnZgQAAoDkAHz/cT82AAgA0gLw/cct2QAgABAACAAB+N2O1LuyAbABQAAgABAACAAEAAIAAYAAQAAgABAACAAEcAl16n7e7soGAAGAAEAACMDvdqTekg2ADQACsN8JvB8bABsABGDLE3gzNgA2gKeO1DuxAbABPHie/9TbsAGwATx7nn8BgAA8fm5AACbA2QUAAvAQOrUATIPzCsBMOKkAQACeRmcUgPlwOgGYEucSgAacSAAacJaLGua2uIV9fatG3wawCnxyAWjAZ/YVyNcho28DWAU+oQ1gFRh9AcjA6AtABkZfADIw+gLg0BLMvQASSzD3AsjqwcQLAIo/hIEAQAAgABAACAAEAAIAAYAAQAAgABAACAAEAAIAAYAAQAAgAAQAAgABgABAACAAEAAIAAQAAgABgABAACAAEAAIAAQAAgABgABAACAAEAAIAAQAAgABgABAACAAEAAIAAQAAgABgABAACAAEAAIAAQAAgABgABAACAAEAAIAAQAAgABIABXgABAACAAEACk+ADy4NUc26mDSgAAAABJRU5ErkJggg==") }

    /** The label transparent, the rest opaque. */
    val maskTransparent: ByteArray by lazy { decode("iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAYAAABccqhmAAACbUlEQVR42u3dwQkAIAwEwYvYf8vahBCIMyXcY8lLK8kJ8KVlAhAAQAAAAQAEABAAQAAAAQAEABAAQAAAAQAEABAAQAAAAQAEABAAQACATtsE7coE3qV0AQACAAgAIACAAAACAAgAIACAAAACAAgAIACAAAACAAgAIACAAAACAAIACAAgAIAAAAIACACQkZ9S+JQBXACAAAACAAgAIACAAAACAAgAIACAAAACAAgAIACAAAACAAgAIACAAAACAAgAIACAAAACAAgAIACAAAACAAgAIACAAAACAAgAIACAAAACAAgACAAgAIAAAAIACAAgAIAAAAIACAAgAIAAAAIACAAgAIAAAAIACAAgAIAAAAIACAAgAIAAAAIACAAgAIAAAAIACAAgAIAAAAIACAAgAIAAAAIACAAIACAAgAAAAgAIACAAgAAAAgAIACAAgAAAAgAIACAAgAAAAgAIACAAgAAAAgAIACAAgAAAAgAIACAAgAAAAgAIACAAgAAAAgAIACAAgAAAAgAIAAgAIACAAAACAAgAIACAAAACAAgAIACAAAACAAgAIACAAAACAAgAIACAAAACAAgAIACAAAACAAgAIACAAAACAAgAIACAAAACAAgAIACAAAACAAJgAhAAQAAAAQAEABAAQAAAAQAEABAAQAAAAQAEABAAQAAAAQAEABAAQAAAAQAEABAAQAAAAQAEABAAQAAAAQAEABAAQAAAAQAEABAAQAAAAQAEAAQAEABAAAABAAQAEABAAAABAAQAEABAAAABAAQAEABAAAABAAQAEABAAAABAAQAEABAAAABAAQAEABAAIAHLtkgBP9zEn45AAAAAElFTkSuQmCC") }

    /** The label white, the rest black. */
    val maskWhite: ByteArray by lazy { decode("iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAIAAADTED8xAAABA0lEQVR42u3TwQ0AIAwDsZb9dw4TwLMCyR4h0VUBAAAAAAAAAAAAAAAAAAAvaxPcJfn+4/by0TIBAgABgABAACAAEAAIAAQAAgABgABAACAAEAAIAAQAAgABgABAACAAEAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACYtwGHrAMyYKVO6wAAAABJRU5ErkJggg==") }

    private fun decode(b64: String): ByteArray = Base64.getDecoder().decode(b64)
}
